name: test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - dev
    paths:
      - '**.js'
      - '**.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - '**.js'
      - '**.ts'
      - 'package.json'
      - 'pnpm-lock.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Test
        run: pnpm run build && ls -lah dist/